### ISSUE TITLE
Internal server error when manually retrying a delayed job

### ISSUE THREAD

**Issue by joshbenaron** [felixmosh/bull-board#323]
Hey,

I have a job delayed upon a 3rd attempt. I press retry on the job in the delayed section and then I get an internal server error

![image](https://user-images.githubusercontent.com/73971531/132338591-cbb463d4-e5fb-4f20-88f1-259f5b6c0617.png)

**Comment by felixmosh** [comment]
Can you open the console and check what is the entire error?

Can you give a reproduction steps?

**Comment by felixmosh** [comment]
@joshbenaron ping?

**Comment by djdmbrwsk** [comment]
Getting this error too, console says:
```
Retried job not failed
    at Job.retry (node_modules/bullmq/dist/classes/job.js:556:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async retryJob (node_modules/@bull-board/api/dist/src/handlers/retryJob.js:7:5)
    at async node_modules/@bull-board/express/dist/ExpressAdapter.js:61:34
```

**Comment by felixmosh** [comment]
@djdmbrwsk can you elaborate what do you get on the server side / client side?
How I can reproduce the issue?

**Comment by felixmosh** [comment]
So the bug is in the UI, the retry button should appear only on `failed` tab

**Comment by djdmbrwsk** [comment]
That would be the simple fix, but I think it could be interesting to allow users to execute a delayed job immediately too. Useful for this scenario, but unsure of other scenarios...maybe too dangerous.

**Comment by felixmosh** [comment]
@djdmbrwsk thank you for the explanation 🙏🏼

**Comment by felixmosh** [comment]
> That would be the simple fix, but I think it could be interesting to allow users to execute a delayed job immediately too. Useful for the retry scenario, but unsure of other scenarios...maybe too dangerous.

Delayed jobs has promote button for this

**Comment by djdmbrwsk** [comment]
> Delayed jobs has promote button for this

Interesting! I thought I saw a PR for this, but didn't notice it in the UI...
