### ISSUE TITLE
Cannot clean unknown queue type 1000

### ISSUE THREAD

**Issue by DCampagnola** [felixmosh/bull-board#382]
I cannot clean completed messages with the button "clean all".
Apis throws the following error:

```
{
    "error": "Internal server error",
    "message": "Cannot clean unknown queue type 1000",
    "details": "Error: Cannot clean unknown queue type 1000\n    at /node_modules/bull/lib/queue.js:1221:13\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async cleanAll (/node_modules/@bull-board/api/dist/src/handlers/cleanAll.js:8:5)\n    at async /node_modules/@bull-board/express/dist/ExpressAdapter.js:61:34"
}
```

bull-board version is 3.9.4

**Comment by felixmosh** [comment]
Thank you for reporting this issue.

Can you elaborate? what is you queue name?

**Comment by DCampagnola** [comment]
Thanks for the answer
This issue applies with all queues I have (for example one is called "update-models").
I'm using bull-board with express in the nestjs framework which is deployed in a Kubernetes deployment with a private service that I'm accessing through [telepresence](https://telepresence.io).
I've seen that in local, connected to the same Redis instance, clean button does work fine but I don't know why.

**Comment by felixmosh** [comment]
Ok, thanx for the info.

Looks like the error is thrown from https://github.com/OptimalBits/bull/blob/11b5e5b5860b1bdd7b6138572e128a53d381b770/lib/queue.js#L1258

Which suggests that the query param is not propagated properly, I need an access to debug it.

**Comment by Kannndev** [comment]
For someone who faces this in the future. I also tumbled into this and after debugging I found that I was initializing my queue with wrong adapter in createBullBoard.queue params. I was using bull and I was using BullMQAdapter (this needs to be used with bullmq package). I switched to BullAdapter and it started working.
