### ISSUE TITLE
Bull-board UI not working on v3.10.1 but working fine on v3.10.0

### ISSUE THREAD

**Issue by rakalicious** [felixmosh/bull-board#391]
Getting error (status - 500) for api api/queues?activeQueue=send_messages&page=1
Error - 
```json
{"error":"Internal server error","message":"Cannot read property 'attemptsMade' of null","details":"TypeError: Cannot read property 'attemptsMade' of null\n    at /app/node_modules/@bull-board/api/dist/src/queueAdapters/bull.js:29:13\n    at Array.map (<anonymous>)\n    at /app/node_modules/@bull-board/api/dist/src/queueAdapters/bull.js:28:80\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /app/node_modules/@bull-board/api/dist/src/handlers/queues.js:75:15\n    at async Promise.all (index 0)\n    at async Object.queuesHandler [as handler] (/app/node_modules/@bull-board/api/dist/src/handlers/queues.js:90:39)\n    at async /app/node_modules/@bull-board/express/dist/ExpressAdapter.js:65:34"}
```

<img width="671" alt="error" src="https://user-images.githubusercontent.com/20751107/160404267-a0e2b861-ddb9-46c7-aa09-6210dcb557d2.png">

- Mentioned the version as some changes were made related to attemptsMade in v3.10.1 due to this [issue](https://github.com/felixmosh/bull-board/issues/386)
- Not sure if its related but got this error when connected to elasticache but not when connected to redis-server (server on local)
- on opening /bull , it redirects to bull/queue/send_messages and then above error
Related Code
```javascript
// bull.js
const Queue = require("bull")
const { createBullBoard } = require("@bull-board/api")
const { BullAdapter } = require("@bull-board/api/bullAdapter")
const { ExpressAdapter } = require("@bull-board/express")

const serverAdapter = new ExpressAdapter()

const bullRedisOption = {
  host: process.env.REDIS_HOST,
  port: process.env.REDIS_PORT,
}

let sendMessageQueue = new Queue("send_messages", {
  redis: bullRedisOption,
  prefix: globalKeys.bullPrefix,
})

const { addQueue, removeQueue, setQueues, replaceQueues } = createBullBoard({
  queues: [new BullAdapter(sendMessageQueue)],
  serverAdapter: serverAdapter,
})

serverAdapter.setBasePath("/bull")
let router = serverAdapter.getRouter()

module.exports = {
  router,
  sendMessageQueue
}
```
```javascript
//in server.js
const bull = require('./config/bull')
app.use('/bull', bull.router);

```
```javascript
//consumers.js
const bull = require('../config/bull')
const { processScheduledMessage } = require("./communication_worker")

// concurrency = 10
bull.sendMessageQueue.process("scheduled_messages", 10, async (job, done) => {
  return await processScheduledMessage(job.data, done)
})

bull.sendMessageQueue.on("completed", function (job, result) {
  console.log(
    `sendMessageQueue job done with result id ${job.id} data ${JSON.stringify(
      job.data
    )} opts ${JSON.stringify(job.opts)} result ${JSON.stringify(result)}`
  )
  redisClient.deleteKey(`${globalKeys.bullPrefix}:send_messages:${job.id}`) //- this deletes entry of job from ui as well 
})

bull.sendMessageQueue.on('failed', function (job, result) {
  console.log(`sendMessageQueue job failed with id ${job.id} reason ${job.failedReason} trace ${job.stacktrace}`)
})
 
```

**Comment by felixmosh** [comment]
Thank you for reporting this detailed report, I'll investigate it asap.

**Comment by felixmosh** [comment]
Can you check if `v3.10.2` solves the issue?

**Comment by rakalicious** [comment]
v3.10.2 resolves the issue
Thanks
