### ISSUE TITLE
[Package development] error TS2307: Cannot find module '@bull-board/x' or its corresponding type declarations.

### ISSUE THREAD

**Issue by KelseyDH** [felixmosh/bull-board#437]
Hi I recently forked `bull-board`, looking into making package updates.  When I checked out the repo and followed the instructions laid out in the README for developing on it, I got a typescript error when running `yarn && yarn start:dev` at the repo's root directory:

```
yarn install v1.22.15
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info msgpackr-extract-darwin-arm64@1.1.0: The CPU architecture "x64" is incompatible with this module.
info "msgpackr-extract-darwin-arm64@1.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info msgpackr-extract-linux-arm@1.1.0: The platform "darwin" is incompatible with this module.
info "msgpackr-extract-linux-arm@1.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info msgpackr-extract-linux-arm@1.1.0: The CPU architecture "x64" is incompatible with this module.
info msgpackr-extract-linux-arm64@1.1.0: The platform "darwin" is incompatible with this module.
info "msgpackr-extract-linux-arm64@1.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info msgpackr-extract-linux-arm64@1.1.0: The CPU architecture "x64" is incompatible with this module.
info msgpackr-extract-linux-x64@1.1.0: The platform "darwin" is incompatible with this module.
info "msgpackr-extract-linux-x64@1.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info msgpackr-extract-win32-x64@1.1.0: The platform "darwin" is incompatible with this module.
info "msgpackr-extract-win32-x64@1.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
warning " > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2".
warning "workspace-aggregator-47515b77-7911-4ae7-aef4-5389157763c4 > @bull-board/api > ioredis-mock@7.2.0" has unmet peer dependency "ioredis@4.x".
[4/4] 🔨  Building fresh packages...
✨  Done in 11.66s.
yarn run v1.22.15
$ concurrently "yarn start:dev:ui" "yarn start:dev:server"
$ ts-node-dev --rs example.ts
$ lerna run --scope @bull-board/ui start
[0] lerna notice cli v4.0.0
[0] lerna notice filter including "@bull-board/ui"
[0] lerna info filter [ '@bull-board/ui' ]
[0] lerna info Executing command in 1 package: "yarn run start"
[1] [INFO] 15:53:25 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.6.3)
[1] Compilation error in /Users/KelseyDH/bull-board/example.ts
[1] [ERROR] 15:53:29 ⨯ Unable to compile TypeScript:
[1] example.ts(5,31): error TS2307: Cannot find module '@bull-board/api/dist/src/queueAdapters/bullMQ' or its corresponding type declarations.
[1] example.ts(6,29): error TS2307: Cannot find module '@bull-board/api/dist/src/queueAdapters/bull' or its corresponding type declarations.
[1] example.ts(7,33): error TS2307: Cannot find module '@bull-board/api' or its corresponding type declarations.
[1] example.ts(8,32): error TS2307: Cannot find module '@bull-board/express' or its corresponding type declarations.
[1]
```

How can I get the NPM package to build locally without these errors?

**Comment by felixmosh** [comment]
Pay attention that it is running example.ts file.

You should remove the /dist/ from its import paths.

**Comment by KelseyDH** [comment]
Thank you!  Replacing that code in the `example.ts` seems to work.  But now when I open the UI at `https://localhost:3000/ui` I get `Error: Failed to lookup view "index.ejs" in views directory "/bull-board/packages/ui/dist"`. E.g.:

 
```
=>. yarn && yarn start:dev
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 1.13s.
yarn run v1.22.15
$ concurrently "yarn start:dev:ui" "yarn start:dev:server"
$ ts-node-dev --rs example.ts
$ lerna run --scope @bull-board/ui start
[0] lerna notice cli v4.0.0
[1] [INFO] 09:41:56 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.6.3)
[0] lerna notice filter including "@bull-board/ui"
[0] lerna info filter [ '@bull-board/ui' ]
[0] lerna info Executing command in 1 package: "yarn run start"
[1] Running on 3000...
[1] For the UI, open http://localhost:3000/ui
[1] Make sure Redis is running on port 6379 by default
[1] To populate the queue, run:
[1]   curl http://localhost:3000/add?title=Example
[1] To populate the queue with custom options (opts), run:
[1]   curl http://localhost:3000/add?title=Test&opts[delay]=10
[1] Error: Failed to lookup view "index.ejs" in views directory "/bull-board/packages/ui/dist"
[1]     at Function.render (/bull-board/node_modules/express/lib/application.js:580:17)
[1]     at ServerResponse.render (/bull-board/node_modules/express/lib/response.js:1017:7)
[1]     at viewHandler (/bull-board/packages/express/src/ExpressAdapter.ts:90:11)
[1]     at Layer.handle [as handle_request] (/bull-board/node_modules/express/lib/router/layer.js:95:5)
[1]     at next (/bull-board/node_modules/express/lib/router/route.js:137:13)
[1]     at Route.dispatch (/bull-board/node_modules/express/lib/router/route.js:112:3)
[1]     at Layer.handle [as handle_request] (/bull-board/node_modules/express/lib/router/layer.js:95:5)
[1]     at /bull-board/node_modules/express/lib/router/index.js:281:22
[1]     at param (/bull-board/node_modules/express/lib/router/index.js:360:14)
[1]     at param (/bull-board/node_modules/express/lib/router/index.js:371:14)
```

**Comment by felixmosh** [comment]
Try to run yarn build before, so it will copy that file (sorry for this)

**Comment by KelseyDH** [comment]
Ah that's it, reverting back to the original unchanged code, and running `yarn && yarn run build && yarn start:dev` is all I needed to get it running.  Thank you!

**Comment by felixmosh** [comment]
But if you want to develop something you will need to consume the code from src (inside example.ts)

**Comment by felixmosh** [comment]
I've updated Readme & `example.ts` to be more dev oriented.
Thank you for reporting this issue.
