### ISSUE TITLE
Any plan to support newer versions of bullmq where Scheduler is depricated?

### ISSUE THREAD

**Issue by jRexhmati** [felixmosh/bull-board#474]
At the moment I get an error when integrating the existing version of bull-board and bullmq@2.3.1 

It looks like bull-board is trying to access some old methods of bullmq which have been deprecated in newer versions

  TypeError: this.queue.getJobCounts is not a function
      at BullMQAdapter.getJobCounts (node_modules/@bull-board/api/src/queueAdapters/bullMQ.ts:34:23)
      at node_modules/@bull-board/api/src/handlers/queues.ts:80:34
      at Array.map (<anonymous>)
      at getAppQueues (ode_modules/@bull-board/api/src/handlers/queues.ts:72:11)
      at Object.queuesHandler [as handler] (node_modules/@bull-board/api/src/handlers/queues.ts:110:43)
      at node_modules/@bull-board/koa/src/KoaAdapter.ts:123:40

**Comment by felixmosh** [comment]
I've tested it on my main app (which got updated to latest bullMQ) and it seemed to work properly.

Can you check that you've passed the queue to the adapter?
