### ISSUE TITLE
Error cleanall completed jobs: user_script:20: attempt to compare number with nil

### ISSUE THREAD

**Issue by thearchitectxy** [felixmosh/bull-board#542]
Hi , despite seperate the BullMQ and Bull adapters , i still keep getting the 500 error when trying to delete, clean all, retry or any action
```js
require('./start');

const express = require('express');
const {
  createBullBoard,
} = require('@bull-board/api')
const {
  BullAdapter,
} = require('@bull-board/api/bullAdapter')

const {
  BullMQAdapter
} = require('@bull-board/api/bullMQAdapter')
const {
  ExpressAdapter
} = require('@bull-board/express')

const serverAdapter = new ExpressAdapter();
const serverAdapterV2 = new ExpressAdapter();

const QueueAdapters = []
const MQQueueAdapters = []
QUEUES.forEach((queue) => {
  const InitializerQueues = require('@initializer/queues');
  QueueAdapters.push(new BullAdapter(InitializerQueues[queue]))
})
MQ_QUEUES.forEach((queue) => {
  const InitializerQueues = require('@initializer/queues');
  MQQueueAdapters.push(new BullMQAdapter(InitializerQueues[queue], {
    readOnlyMode: false
  }))
})

const {
  addQueue,
  removeQueue,
  setQueues,
  replaceQueues
} = createBullBoard({
  queues: QueueAdapters,
  serverAdapter: serverAdapter
})

const {} = createBullBoard({
  queues: MQQueueAdapters,
  serverAdapter: serverAdapterV2
})

const username = process.env.BASIC_AUTH_USERNAME;
const password = process.env.BASIC_AUTH_PASSWORD;
console.log(username, password);
serverAdapter.setBasePath('/queue/monitor')
serverAdapterV2.setBasePath('/v2/queue/monitor')
```

**Comment by thearchitectxy** [comment]
cc @felixmosh  thanks

**Comment by thearchitectxy** [comment]
using latest bullmq 3.7.0, for the normal bull queues deleting, cleanup works fine, only bullMQ has issues

**Comment by felixmosh** [comment]
Try to update to latest v4 version.
Anyway, this is not related to the board, probably you are not passing an instance of a specific queue...

What initilizersQueues[queue] returns?

**Comment by thearchitectxy** [comment]
> Try to update to latest v4 version. Anyway, this is not related to the board, probably you are not passing an instance of a specific queue...
> 
> What initilizersQueues[queue] returns?

i have latest 4.12.1 but same error
Constant.js
```

exports.MQ_QUEUES_LIST = [
    "DocumentTranscriptionQueue",
    "DocumentTranscriptionResultsQueue",
    "DocumentPlagiarismCheckQueue",
    "DocumentPlagiarismCheckResultQueue",
    "DocumentVectorEmbeddingQueue",
    "DocumentVectorEmbeddingResultsQueue",
    "DocumentQueryAIQueue",
    "DocumentQueryAIResultsQueue"
]
```
intiializers/queue.js
```
const Queue = require("bull");
const QueueMQ = require('bullmq');
const Redis = require("ioredis");
const {
    CONFIG,
    QUEUES_LIST,
    MQ_QUEUES_LIST
} = require('@helpers/constants')
const client_bus = new Redis(CONFIG.REDIS_URI);

console.log(client_bus);
console.log(CONFIG.REDIS_URI);

const QUEUES = QUEUES_LIST;
QUEUES.forEach((queue) => {
    exports[queue] = new Queue(queue, {
        createClient() {
            return client_bus;
        }
    });
})

const MQ_QUEUES = MQ_QUEUES_LIST;
MQ_QUEUES.forEach((queue) => {
    exports[queue] = new QueueMQ.Queue(queue, {
        connection: client_bus
    });
})



// const { ExpressAdapter, createBullBoard, BullAdapter, BullMQAdapter } = require('@bull-board/express');



exports.QUEUES = QUEUES;
exports.MQ_QUEUES = MQ_QUEUES;
```

**Comment by thearchitectxy** [comment]
@felixmosh  queues are seperated all the way between Old Bull and New BullMQ to avoid conflict, yet i can delete,retry bull jobs on /queue/monitor route but on /v2/queue/monitor(bullMQ route) no action works

**Comment by thearchitectxy** [comment]
**Clean All/One Error** 

`{"error":"Internal server error","message":"ERR Number of keys can't be greater than number of args","details":"ReplyError: ERR Number of keys can't be greater than number of args\n    at parseError (/src/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/src/node_modules/redis-parser/lib/parser.js:302:14)"}`

**Retry All/One Error:**
`{"error":"Internal server error","message":"Missing key for job 40. reprocessJob","details":"Error: Missing key for job 40. reprocessJob\n    at Scripts.finishedErrors (/src/node_modules/bullmq/dist/cjs/classes/scripts.js:204:24)\n    at Scripts.reprocessJob (/src/node_modules/bullmq/dist/cjs/classes/scripts.js:490:28)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Promise.all (index 0)\n    at async retryAll (/src/node_modules/@bull-board/api/dist/src/handlers/retryAll.js:8:5)\n    at async /src/node_modules/@bull-board/express/dist/ExpressAdapter.js:66:34"}`


@felixmosh

**Comment by felixmosh** [comment]
How do you know that you are not overriding the same export props?

```js
const Queue = require("bull");
const QueueMQ = require('bullmq');
const Redis = require("ioredis");
const {
    CONFIG,
    QUEUES_LIST,
    MQ_QUEUES_LIST
} = require('@helpers/constants')
const client_bus = new Redis(CONFIG.REDIS_URI);

console.log(client_bus);
console.log(CONFIG.REDIS_URI);

const QUEUES = QUEUES_LIST;
exports.bull = {};
exports.bullMQ = {};

QUEUES.forEach((queue) => {
    exports.bull[queue] = new Queue(queue, {
        createClient() {
            return client_bus;
        }
    });
})

const MQ_QUEUES = MQ_QUEUES_LIST;
MQ_QUEUES.forEach((queue) => {
    exports.bullMQ[queue] = new QueueMQ.Queue(queue, {
        connection: client_bus
    });
})

```

```js
require('./start');

const express = require('express');
const {
  createBullBoard,
} = require('@bull-board/api')
const {
  BullAdapter,
} = require('@bull-board/api/bullAdapter')

const {
  BullMQAdapter
} = require('@bull-board/api/bullMQAdapter')
const {
  ExpressAdapter
} = require('@bull-board/express')

const InitializerQueues = require('@initializer/queues');

const serverAdapter = new ExpressAdapter();
const serverAdapterV2 = new ExpressAdapter();

const QueueAdapters = QUEUES.map(queueName => new BullAdapter(InitializerQueues.bull[queueName]))
const MQQueueAdapters = MQ_QUEUES.map(queueName => new BullMQAdapter(InitializerQueues.bullMQ[queueName]))

createBullBoard({
  queues: QueueAdapters,
  serverAdapter: serverAdapter
})

createBullBoard({
  queues: MQQueueAdapters,
  serverAdapter: serverAdapterV2
})

const username = process.env.BASIC_AUTH_USERNAME;
const password = process.env.BASIC_AUTH_PASSWORD;
console.log(username, password);
serverAdapter.setBasePath('/queue/monitor')
serverAdapterV2.setBasePath('/v2/queue/monitor')
```

**Comment by thearchitectxy** [comment]
@felixmosh you were right it was the connection, i make seperate now all is fine thanks
