### ISSUE TITLE
Getting an error: "No .lua files found!"

### ISSUE THREAD

**Issue by hilja** [felixmosh/bull-board#567]
The GUI loads fine but I get a 500 error when the board is trying to reach `http://localhost:3000/admin/queues/api/queues?activeQueue=&page=1&jobsPerPage=10`:

```json
{
  "error": "Internal server error",
  "message": "No .lua files found!",
  "details": "Error: No .lua files found!\n    at loadScripts (/Users/bob/web/my-project/build/server.js:69539:15)\n    at /Users/bob/web/my-project/build/server.js:69529:19"
}
```

I'm on esbuild. Node version v18.16.0.

**Comment by hilja** [comment]
Ah, apparently I need to copy the `.lua` scripts over to my `/build` dir https://github.com/OptimalBits/bull/issues/2409#issuecomment-1213322957

**Comment by hilja** [comment]
That works! For anyone with the same issue, you can put a simple copy script in your `package.json`:

```json
"scripts": {
  "dev:bull": "cp node_modules/bull/lib/commands/*.lua build/"
}
```
