### ISSUE TITLE
Fastify Adapter Deprecation Warning

### ISSUE THREAD

**Issue by coder797** [felixmosh/bull-board#628]
```
(node:97554) [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.
    at Object.emit (/[...]/node_modules/process-warning/index.js:55:13)
    at _Request.get (/[...]/node_modules/fastify/lib/request.js:175:15)
    at getRequestedPath (/[...]/node_modules/@fastify/view/index.js:190:59)
    at _Reply.viewEjs (/[...]/node_modules/@fastify/view/index.js:388:27)
    at _Reply.view (/[...]/node_modules/@fastify/view/index.js:131:14)
    at Object.handler (/[...]/node_modules/@bull-board/fastify/src/FastifyAdapter.ts:128:26)
    at preHandlerCallback (/[...]/node_modules/fastify/lib/handleRequest.js:137:37)
    at validationCompleted (/[...]/node_modules/fastify/lib/handleRequest.js:121:5)
    at preValidationCallback (/[...]/node_modules/fastify/lib/handleRequest.js:98:5)
    at handler (/[...]/node_modules/fastify/lib/handleRequest.js:75:7)
    at handleRequest (/[...]/node_modules/fastify/lib/handleRequest.js:24:5)
    at runPreParsing (/[...]/node_modules/fastify/lib/route.js:568:5)
    at next (/[...]/node_modules/fastify/lib/hooks.js:237:9)
    at Object.<anonymous> (/[...]/node_modules/@fastify/view/index.js:140:7)
    at hookIterator (/[...]/node_modules/fastify/lib/hooks.js:409:10)
    at next (/[...]/node_modules/fastify/lib/hooks.js:243:18)
    at handleResolve (/[...]/node_modules/fastify/lib/hooks.js:254:7)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
(node:97554) [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.
    at Object.emit (/[...]/node_modules/process-warning/index.js:55:13)
    at _Request.get (/[...]/node_modules/fastify/lib/request.js:175:15)
    at getRequestedPath (/[...]/node_modules/@fastify/view/index.js:190:59)
    at _readCallback (/[...]/node_modules/@fastify/view/index.js:264:29)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
    at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17)

```

Getting this warning every now and then 
Im on the latest bull board version and with the latest fastify adapter

**Comment by felixmosh** [comment]
Try `v5.8.4`, it should solve these deprecation warnings
