### ISSUE TITLE
Error when adding jobs using Koa + BullBoard

### ISSUE THREAD

**Issue by tim-trewartha** [felixmosh/bull-board#841]
Hi! We are using BullBoard and it is definitely a useful tool, but we are hitting an issue when adding jobs using the UI. We get this error response and a 500:
```
{
    "error": "Internal server error",
    "message": "Cannot destructure property 'name' of 'req.body' as it is undefined.",
    "details": "TypeError: Cannot destructure property 'name' of 'req.body' as it is undefined.\n    at addJob (/app/node_modules/.pnpm/@bull-board+api@5.21.4_@bull-board+ui@5.21.4/node_modules/@bull-board/api/src/handlers/addJob.ts:10:11)\n    at Object.handler (/app/node_modules/.pnpm/@bull-board+api@5.21.4_@bull-board+ui@5.21.4/node_modules/@bull-board/api/src/providers/queue.ts:33:12)\n    at <anonymous> (/app/node_modules/.pnpm/@bull-board+koa@5.21.4_@types+koa@2.13.5_dot@1.1.3_handlebars@4.7.8_lodash@4.17.21_mustache@4.2.0_underscore@1.13.6/node_modules/@bull-board/koa/src/KoaAdapter.ts:134:40)\n    at dispatch (/app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)\n    at /app/node_modules/.pnpm/koa-router@10.1.1/node_modules/koa-router/lib/router.js:372:16\n    at dispatch (/app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)\n    at /app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12\n    at dispatch (/app/node_modules/.pnpm/koa-router@10.1.1/node_modules/koa-router/lib/router.js:377:31)\n    at dispatch (/app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)\n    at /app/node_modules/.pnpm/koa-mount@4.0.0/node_modules/koa-mount/index.js:52:32\n    at dispatch (/app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)\n    at views (/app/node_modules/.pnpm/koa-views@7.0.2_@types+koa@2.13.5_dot@1.1.3_ejs@3.1.10_handlebars@4.7.8_lodash@4.17.21_mustache@4.2.0_underscore@1.13.6/node_modules/koa-views/src/index.js:91:12)\n    at dispatch (/app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)\n    at <anonymous> (/app/node_modules/.pnpm/@bull-board+koa@5.21.4_@types+koa@2.13.5_dot@1.1.3_handlebars@4.7.8_lodash@4.17.21_mustache@4.2.0_underscore@1.13.6/node_modules/@bull-board/koa/src/KoaAdapter.ts:96:15)\n    at dispatch (/app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)\n    at /app/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12"
}
```

Our setup looks more or less like this:

```
import { createBullBoard } from '@bull-board/api';
import { BullMQAdapter } from '@bull-board/api/bullMQAdapter';
import { KoaAdapter } from '@bull-board/koa';
import { Queue, type ConnectionOptions } from 'bullmq';
import bodyParser from 'koa-bodyparser';
import type Koa from 'koa';

import { startKoaServer, type StartupFunctionConfig } from '@shared/koa-utils';


const redisConnectionSettings: ConnectionOptions = {
    ....
};

const allQueueNames = [
    'example-queue'
];

function setupKoaServer<Context extends Koa.ParameterizedContext>({
    application,
    router,
}: StartupFunctionConfig<Context>): Koa {
    const serverAdapter = new KoaAdapter();

    const allQueueAdapters = allQueueNames.map(
        (x) =>
            new BullMQAdapter(
                new Queue(x, {
                    connection: redisConnectionSettings,
                })
            )
    );

    createBullBoard({
        queues: allQueueAdapters,
        serverAdapter,
        options: {
            uiConfig: {
                boardTitle: 'BullMQ Dash',
            },
        },
    });

    serverAdapter.setBasePath('/ui');
    application
        .use(bodyParser())
        .use(serverAdapter.registerPlugin())
        .use(router.routes())
        .use(router.allowedMethods());

    return application;
}

// This is a lightweight re-usable function which we use in multiple services 
void startKoaServer('bullboard', {
    koaSetupFunction: setupKoaServer,
    logger: defaultLogger,
    port: settings.port,
});
```

Thanks for any pointers! for some reason adding the body parser is not sufficient and am not sure what we are missing

**Comment by felixmosh** [comment]
Hi, thank you for reporting this issue.
Do you see the job name in the network tab?

**Comment by tim-trewartha** [comment]
Hi! Yup I do see the data:

CURL:
```
curl 'https://bull-board-local.test.com/ui/api/queues/example/add' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'content-type: application/json' \ \
  -H 'priority: u=1, i' \
  -H 'sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  --data-raw '{"name":"PollConsentStatus","data":{"a":"b"},"options":{}}'
```

![image](https://github.com/user-attachments/assets/e3aad7c3-d8c9-412d-ae03-7e246e0e7b6d)

**Comment by felixmosh** [comment]
Ok, so it probably get lost in KoaAdapter somewhere...

**Comment by felixmosh** [comment]
Can you confirm that `v6.3.0` solves this issue for you?

**Comment by tim-trewartha** [comment]
Yup! appears to be working now - thanks so much!

**Comment by Jaywaa** [comment]
Thanks for fixing @felixmosh! 🎉
