### ISSUE TITLE
Release 6.2.2 issue for non-bull users

### ISSUE THREAD

**Issue by vanwalj** [felixmosh/bull-board#844]
Hello!

We're using BullBoard with BullMQ (and absolutely loving it!). However, it seems that the [6.2.2 release of BullBoard has a dependency on Bull](https://github.com/felixmosh/bull-board/commit/d0e42c7bf689400a4768e806ed1c774bafe77cab), which causes it to crash on startup if Bull isn't installed.

Thanks!

```
Error: Cannot find module 'bull'
server-1      | [1] Require stack:
server-1      | [1] - /home/node/app/node_modules/@bull-board/api/dist/src/queueAdapters/bull.js
server-1      | [1] - /home/node/app/node_modules/@bull-board/api/bullAdapter.js
server-1      | [1] - /home/node/app/src/infrastructure/JobQueue.ts
server-1      | [1] - /home/node/app/src/application/jobs/[redacted].ts
server-1      | [1] - /home/node/app/src/index.ts
server-1      | [1]     at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
server-1      | [1]     at Function._load (node:internal/modules/cjs/loader:1075:27)
server-1      | [1]     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
server-1      | [1]     at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
server-1      | [1]     at Module.require (node:internal/modules/cjs/loader:1340:12)
server-1      | [1]     at require (node:internal/modules/helpers:141:16)
server-1      | [1]     at Object.<anonymous> (/home/node/app/node_modules/@bull-board/api/src/queueAdapters/bull.ts:2:1)
server-1      | [1]     at Module._compile (node:internal/modules/cjs/loader:1546:14)
server-1      | [1]     at node:internal/modules/cjs/loader:1689:10
server-1      | [1]     at Object.newLoader [as .js] (/home/node/app/node_modules/pirates/lib/index.js:121:7) {
server-1      | [1]   code: 'MODULE_NOT_FOUND',
server-1      | [1]   requireStack: [
server-1      | [1]     '/home/node/app/node_modules/@bull-board/api/dist/src/queueAdapters/bull.js',
server-1      | [1]     '/home/node/app/node_modules/@bull-board/api/bullAdapter.js',
server-1      | [1]     '/home/node/app/src/infrastructure/JobQueue.ts',
server-1      | [1]     '/home/node/app/src/application/jobs/[redacted].ts',
server-1      | [1]     '/home/node/app/src/index.ts'
server-1      | [1]   ]
server-1      | [1] }
```

**Comment by felixmosh** [comment]
Hi, thank tou for reporting this issue.

It looks like something in your code imports bullAdapter instead of bullMqAdapter, can you check if that true?

**Comment by vanwalj** [comment]
Awesome! Bull is so robust that we've actually been using it incorrectly for the past few months without any issues.

Thanks for all your time and effort, and apologies for the trouble. Closing this now. :)
